## create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"mimi gee",
    "email":"mimi@gmail.com",
    "password":"march2014"
}

# ### get all users
# GET http://localhost:5000/users/

### Get user by id
# GET http://localhost:5000/users/5f1048c31a10bd518fbe6caa

### update user details
PATCH http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE4M2JiOWUxNjRlZjJjNmM4N2MxNDIiLCJpYXQiOjE1OTU0MjM2NzMsImV4cCI6MTU5NTQyNzI3M30.CsZKdTC28K-umWIQJuksmTpl7LSYXlVpyHbrxzZHB9A

{
    "name":"brian sunday",
    "email":"mimi@gmail.com",
    "password":"march2014",
    "age":27

}

### login user
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"mimi@gmail.com",
    "password":"march2014"

}

### find my profile
GET http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1YTNkN2EzNjlhODQ2NjEzMDI0ODAiLCJpYXQiOjE1OTU0MjMxMjgsImV4cCI6MTU5NTQyNjcyOH0.n_cnnOR7z1g-_SAUYZhJB5aKkrb-kadmeOOLyC9aXV

### logout
POST http://localhost:5000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1YTNkN2EzNjlhODQ2NjEzMDI0ODAiLCJpYXQiOjE1OTUyNTk5MTYsImV4cCI6MTU5NTQzMjcxNn0.PPnY8cm1WyOFtDF7-9MRAlUf0wioskun6n0VCuAWH4g


### logout all
POST http://localhost:5000/users/logoutAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1YTNkN2EzNjlhODQ2NjEzMDI0ODAiLCJpYXQiOjE1OTU0MjE2OTEsImV4cCI6MTU5NTQyNTI5MX0.V4nIj08YPkndcXyF5930g_kEKeL2Vf6f2U_lNGfpRv0


### remove my profile
DELETE http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1YTNkN2EzNjlhODQ2NjEzMDI0ODAiLCJpYXQiOjE1OTU0MjMxMjgsImV4cCI6MTU5NTQyNjcyOH0.n_cnnOR7z1g-_SAUYZhJB5aKkrb-kadmeOOLyC9aXV8


### upload avatar
GET http://localhost:5000/users/me/avatar


### get avatar url
GET http://localhost:5000/users/5f183bb9e164ef2c6c87c142/avatar
 

### create a task
POST http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE4M2JiOWUxNjRlZjJjNmM4N2MxNDIiLCJpYXQiOjE1OTU1MDMwNjMsImV4cCI6MTU5NTUwNjY2M30.Cv96YQzL8f2VNxU9IVO2QwFJBd32OLMzDCI0KKyrIv4

{
   "description":"another by brian"
}


### get all task http://localhost:5000/tasks?completed=true
GET http://localhost:5000/tasks?limit=2&skip=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE4M2JiOWUxNjRlZjJjNmM4N2MxNDIiLCJpYXQiOjE1OTU1MDY3ODIsImV4cCI6MTU5NTUxMDM4Mn0.0CvwQ-V21PqM5BaEkuXWa151_34QAoXuaPJ1_6agA0Y


### find task by id
GET http://localhost:5000/tasks/5f106871ee37f75e5455f3a8


### update task
PATCH http://localhost:5000/tasks/5f11e5268571fe1958791237
Content-Type: application/json

{
    "description":"new brian",
    "completed":false

}

###
DELETE http://localhost:5000/tasks/5f106871ee37f75e5455f3a8
